apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker-egbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker-egbh
    app.kubernetes.io/part-of: quarkus
  name: java-quarkus-hello-docker-egbh
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-hello-docker-egbh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-hello-docker-egbh
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/burrzinga-hac-tenant/quarkus/java-quarkus-hello-docker-egbh@sha256:3f9b05a336a045402a00222e6718712d1a71a9ec63eae2b86db27fcbd82f328d
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
