apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-hello-docker-egbh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-hello-docker-egbh
    app.kubernetes.io/part-of: quarkus
  name: java-quarkus-hello-docker-egbh
  namespace: burrzinga-hac-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-quarkus-hello-docker-egbh
status:
  loadBalancer: {}
